/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author The G AppareL Darius
 */
public class MakingPurchases extends javax.swing.JFrame {

        double Hotdog = 1.5;
        double Rice = 0.59;
        double Cola = 3.55;
        double Sprite = 9.5;
        double Subtotal;
        final double tax = 0.13;
        double Grandtotal;
        double taxes;
        int numofhotdog;
        int numofrice;
        int numofcola;
        int numofsprite;
        
         
    public MakingPurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        textField1 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        lblHeader = new javax.swing.JLabel();
        lblHotdog = new javax.swing.JLabel();
        lblRice = new javax.swing.JLabel();
        lblCola = new javax.swing.JLabel();
        lblSprite = new javax.swing.JLabel();
        btnSum = new java.awt.Button();
        txtrice = new javax.swing.JTextField();
        txtsprite = new javax.swing.JTextField();
        txtCola = new javax.swing.JTextField();
        txthotdog = new javax.swing.JTextField();
        lblSubtotal = new javax.swing.JLabel();
        lblTax = new javax.swing.JLabel();
        lblGrandtotal = new javax.swing.JLabel();
        lblAnswersubtotal = new javax.swing.JLabel();
        lblAnswertax = new javax.swing.JLabel();
        lblAnswergrandtotal = new javax.swing.JLabel();

        textField1.setText("textField1");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblHeader.setText("The Eating System");
        lblHeader.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblHotdog.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblHotdog.setText("Hot dog 1.5$");

        lblRice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRice.setText("Rice 0.59$");

        lblCola.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCola.setText("Cola 3.55$");

        lblSprite.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSprite.setText("Sprite 9.5$");

        btnSum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSum.setForeground(new java.awt.Color(255, 51, 51));
        btnSum.setLabel("sum");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, textField1, org.jdesktop.beansbinding.ObjectProperty.create(), btnSum, org.jdesktop.beansbinding.BeanProperty.create("name"));
        bindingGroup.addBinding(binding);

        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });

        txtrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtriceActionPerformed(evt);
            }
        });

        txtsprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspriteActionPerformed(evt);
            }
        });

        txtCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColaActionPerformed(evt);
            }
        });

        txthotdog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthotdogActionPerformed(evt);
            }
        });

        lblSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSubtotal.setText("Subtotal");

        lblTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTax.setText("Tax(13%)");

        lblGrandtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGrandtotal.setText("Grandtotal");

        lblAnswersubtotal.setText("...");

        lblAnswertax.setText("...");

        lblAnswergrandtotal.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCola)
                                    .addComponent(lblSprite)
                                    .addComponent(lblRice))
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCola, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsprite, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHotdog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txthotdog, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGrandtotal))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAnswergrandtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnswersubtotal)
                            .addComponent(lblAnswertax))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHotdog)
                            .addComponent(txthotdog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSubtotal)
                            .addComponent(lblAnswersubtotal))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRice)
                            .addComponent(txtrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTax)
                            .addComponent(lblAnswertax))
                        .addGap(31, 31, 31)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblGrandtotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblAnswergrandtotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCola)
                            .addComponent(txtCola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSprite, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsprite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnSum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        
       
        
        Subtotal = Hotdog * numofhotdog + Rice * numofrice + Cola * numofcola + Sprite * numofsprite; 
       
        lblAnswersubtotal.setText(String.valueOf(Subtotal));
        
        taxes = tax * (Hotdog * numofhotdog + Rice * numofrice + Cola * numofcola + Sprite * numofsprite);
        
        lblAnswertax.setText(String.valueOf(taxes));
        
        Grandtotal = Subtotal + taxes;
        
        lblAnswergrandtotal.setText(String.valueOf(Grandtotal));
        
     
    }//GEN-LAST:event_btnSumActionPerformed

    private void txthotdogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthotdogActionPerformed
      numofhotdog = Integer.parseInt(txthotdog.getText());
    }//GEN-LAST:event_txthotdogActionPerformed

    private void txtriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtriceActionPerformed
      numofrice = Integer.parseInt(txtrice.getText());  
    }//GEN-LAST:event_txtriceActionPerformed

    private void txtColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColaActionPerformed
      numofcola = Integer.parseInt(txtCola.getText());
    }//GEN-LAST:event_txtColaActionPerformed

    private void txtspriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspriteActionPerformed
      numofsprite = Integer.parseInt(txtsprite.getText());

    }//GEN-LAST:event_txtspriteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       /* Set the Nimb
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Ninot available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new RunnableImpl());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAnswergrandtotal;
    private javax.swing.JLabel lblAnswersubtotal;
    private javax.swing.JLabel lblAnswertax;
    private javax.swing.JLabel lblCola;
    private javax.swing.JLabel lblGrandtotal;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblHotdog;
    private javax.swing.JLabel lblRice;
    private javax.swing.JLabel lblSprite;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTax;
    private java.awt.TextField textField1;
    private javax.swing.JTextField txtCola;
    private javax.swing.JTextField txthotdog;
    private javax.swing.JTextField txtrice;
    private javax.swing.JTextField txtsprite;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            new MakingPurchases().setVisible(true);
        }
    }
}
